spring:
  datasource:
    url: jdbc:mysql://localhost:3306/provider?createDatabaseIfNotExist=true
    username: root
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
      